"""Ports consumed by the application layer and implemented by adapters."""

from typing import Iterable, Protocol

from .domain import (
    AuditEvent,
    MembershipRole,
    Organization,
    OrganizationMembership,
    Permission,
    Role,
    Site,
    UserProfile,
)


class CoreStore(Protocol):
    organizations: dict[str, Organization]
    sites: dict[str, Site]
    users: dict[str, UserProfile]
    memberships: dict[str, OrganizationMembership]
    permissions: dict[str, Permission]
    roles: dict[str, Role]
    membership_roles: dict[str, MembershipRole]

    def record_audit(self, event: AuditEvent) -> None: ...

    def save_organization(self, entity: Organization) -> None: ...
    def save_site(self, entity: Site) -> None: ...
    def save_user(self, entity: UserProfile) -> None: ...
    def save_membership(self, entity: OrganizationMembership) -> None: ...
    def save_permission(self, entity: Permission) -> None: ...
    def save_role(self, entity: Role) -> None: ...
    def save_membership_role(self, entity: MembershipRole) -> None: ...
    def get_organization(self, entity_id: str) -> Organization | None: ...
    def get_site(self, entity_id: str) -> Site | None: ...
    def get_user(self, entity_id: str) -> UserProfile | None: ...
    def get_membership(self, entity_id: str) -> OrganizationMembership | None: ...
    def get_role(self, entity_id: str) -> Role | None: ...
    def all_sites(self) -> Iterable[Site]: ...
    def all_memberships(self) -> Iterable[OrganizationMembership]: ...
    def all_roles(self) -> Iterable[Role]: ...
    def all_membership_roles(self) -> Iterable[MembershipRole]: ...
    def all_permissions(self) -> Iterable[Permission]: ...


class AuditSink(Protocol):
    def record_audit(self, event: AuditEvent) -> None: ...
